apiVersion: v2
name: bita-esm
description: BITA Enterprise Service Manager - Backend and Frontend
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - esm
  - enterprise
  - service-management
maintainers:
  - name: BITA Team
    email: team@bita.ir
dependencies: []
