-- Runs after Hibernate's create-drop DDL (spring.jpa.defer-datasource-initialization=true).
-- ComponentTemplate maps attachment_ids with columnDefinition "bigint[]" (Postgres syntax),
-- which H2 rejects, so Hibernate cannot create these two tables; same columns, H2 array type.
CREATE TABLE IF NOT EXISTS component_template (
    is_active boolean not null,
    is_deleted boolean not null,
    created_at timestamp(6) not null,
    created_by bigint,
    id bigint generated by default as identity,
    updated_at timestamp(6),
    updated_by bigint,
    version bigint,
    component_type varchar(20) not null check (component_type in ('PROCESSOR','BEAN')),
    category varchar(50),
    name varchar(100) not null unique,
    description varchar(500),
    camel_yaml TEXT,
    class_name varchar(255) not null,
    groovy_code TEXT,
    attachment_ids BIGINT ARRAY,
    config_schema jsonb,
    primary key (id)
);

CREATE TABLE IF NOT EXISTS component_template_aud (
    is_active boolean,
    is_deleted boolean,
    revtype smallint,
    created_at timestamp(6),
    created_by bigint,
    id bigint not null,
    rev bigint not null,
    updated_at timestamp(6),
    updated_by bigint,
    component_type varchar(20) check (component_type in ('PROCESSOR','BEAN')),
    category varchar(50),
    name varchar(100),
    description varchar(500),
    camel_yaml TEXT,
    class_name varchar(255),
    groovy_code TEXT,
    attachment_ids BIGINT ARRAY,
    config_schema jsonb,
    primary key (id, rev)
);
