apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bita

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - esm-backend-deployment.yaml
  - esm-frontend-deployment.yaml
  - ingress.yaml
  - network-policy.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/version: "1.0.0"

commonLabels:
  environment: base
